### ISSUE TITLE
feat?: Use static import for `lodash.uniqWith`

### ISSUE THREAD

**Issue by jeswr** [rubensworks/rdf-terms.js#38]
The use of `require` [here](https://github.com/rubensworks/rdf-terms.js/blob/2670d9ec3bfc9f14482bb12035e43df8fd583c8c/lib/TermUtil.ts#L19-L21) can cause some problems when `rdf-terms.js` is a used in React applications (in my case it is because it is a comunica dependency).

In particular, problems arise when doing mock renders in jest. For reference [this](https://github.com/schimatos/shacl-form-react/blob/main/__tests__/form/person-shape-test.tsx) the testing file that is causing the error log, and here is the error:

```bash
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From __tests__/form/person-shape-test.tsx.

      at Object.uniqTerms (node_modules/rdf-terms/lib/TermUtil.js:19:12)
      at Function.getVariables (node_modules/@comunica/actor-query-operation-construct/lib/ActorQueryOperationConstruct.js:20:28)
      at ActorQueryOperationConstruct.runOperation (node_modules/@comunica/actor-query-operation-construct/lib/ActorQueryOperationConstruct.js:28:56)
      at ActorQueryOperationConstruct.run (node_modules/@comunica/bus-query-operation/lib/ActorQueryOperationTyped.js:34:35)
      at ActorQueryOperationConstruct.runObservable (node_modules/@comunica/core/lib/Actor.js:58:29)
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
```

**Comment by rubensworks** [comment]
Moving up the `require` would indeed be a quick fix.

However, now that I look at the code again, there's probably no need for the `lodash.uniqwith` dependency.
Ensuring uniqueness could easily be achieved with a simple `Map` that maps a unique string representation of each term (like the one from `rdf-string`) to the term itself.

In any case, a PR for either solution is welcome.
